import React from 'react';

import Autocomplete from '@material-ui/lab/Autocomplete';

import TextField from '@material-ui/core/TextField';
import { makeStyles } from '@material-ui/core/styles';

const useStyles = makeStyles({
option: {
    fontSize: 15,
    '& > span': {
    marginRight: 10,
    fontSize: 18,
    },
},
});

const CountrySelect = (props) => {
    const classes = useStyles();

    return (
        <Autocomplete
        id="country-select-demo"
        style={{ width: 300 }}
        options={countries}
        classes={{
            option: classes.option,
        }}
        
        autoHighlight
        getOptionLabel={(option) => option.label}
        renderOption={(option) => (
            <React.Fragment>
                {option.label}
            </React.Fragment>
        )}
        name='location'
        onChange={props.change}
        renderInput={(params) => (
            <TextField
            {...params}
            label="Šalis"
            name='location'
            variant="outlined"
            inputProps={{
                ...params.inputProps,
                autoComplete: 'new-password', // disable autocomplete and autofill
            }}          
            />
        )}
    />
    )
};

export default CountrySelect;


const countries = [
    { code: "AF", label: 'Afganistanas'},
    { code: "IE", label: 'Airija'},
    { code: "AX", label: 'Alandų Salos'},
    { code: "AL", label: 'Albanija'},
    { code: "DZ", label: 'Alžyras'},
    { code: "AS", label: 'Amerikos Samoa'},
    { code: "AD", label: 'Andora'},
    { code: "AI", label: 'Angilija'},
    { code: "AO", label: 'Angola'},
    { code: "AQ", label: 'Antarktida'},
    { code: "AG", label: 'Antigva ir Barbuda'},
    { code: "AR", label: 'Argentina'},
    { code: "AM", label: 'Armėnija'},
    { code: "AW", label: 'Aruba'},
    { code: "AU", label: 'Australija'},
    { code: "AT", label: 'Austrija'},
    { code: "AZ", label: 'Azerbaidžanas'},
    { code: "BS", label: 'Bahamos'},
    { code: "BH", label: 'Bahreinas'},
    { code: "BY", label: 'Baltarusija'},
    { code: "BD", label: 'Bangladešas'},
    { code: "BB", label: 'Barbadosas'},
    { code: "BE", label: 'Belgija'},
    { code: "BZ", label: 'Belizas'},
    { code: "BJ", label: 'Beninas'},
    { code: "BM", label: 'Bermuda'},
    { code: "GW", label: 'Bisau Gvinėja'},
    { code: "BO", label: 'Bolivija'},
    { code: "BA", label: 'Bosnija ir Hercegovina'},
    { code: "BW", label: 'Botsvana'},
    { code: "BR", label: 'Brazilija'},
    { code: "BN", label: 'Brunėjus'},
    { code: "BG", label: 'Bulgarija'},
    { code: "BF", label: 'Burkina Fasas'},
    { code: "BI", label: 'Burundis'},
    { code: "BT", label: 'Butanas'},
    { code: "CF", label: 'Centrinės Afrikos Respublika'},
    { code: "TD", label: 'Čadas'},
    { code: "CZ", label: 'Čekija'},
    { code: "CL", label: 'Čilė'},
    { code: "AC", label: 'Dangun Žengimo sala'},
    { code: "DK", label: 'Danija'},
    { code: "VG", label: 'Didžiosios Britanijos Mergelių Salos'},
    { code: "DG", label: 'Diego Garsija'},
    { code: "DM", label: 'Dominika'},
    { code: "DO", label: 'Dominikos Respublika'},
    { code: "CI", label: 'Dramblio Kaulo Krantas'},
    { code: "JE", label: 'Džersis'},
    { code: "DJ", label: 'Džibutis'},
    { code: "EG", label: 'Egiptas'},
    { code: "EC", label: 'Ekvadoras'},
    { code: "ER", label: 'Eritrėja'},
    { code: "EE", label: 'Estija'},
    { code: "ET", label: 'Etiopija'},
    { code: "FO", label: 'Farerų Salos'},
    { code: "FJ", label: 'Fidžis'},
    { code: "PH", label: 'Filipinai'},
    { code: "FK", label: 'Folklando Salos'},
    { code: "GA", label: 'Gabonas'},
    { code: "GY", label: 'Gajana'},
    { code: "GM", label: 'Gambija'},
    { code: "GH", label: 'Gana'},
    { code: "GG", label: 'Gernsis'},
    { code: "GI", label: 'Gibraltaras'},
    { code: "GR", label: 'Graikija'},
    { code: "GD", label: 'Grenada'},
    { code: "GL", label: 'Grenlandija'},
    { code: "GE", label: 'Gruzija'},
    { code: "GU", label: 'Guamas'},
    { code: "GP", label: 'Gvadelupa'},
    { code: "GT", label: 'Gvatemala'},
    { code: "GN", label: 'Gvinėja'},
    { code: "HT", label: 'Haitis'},
    { code: "HN", label: 'Hondūras'},
    { code: "IN", label: 'Indija'},
    { code: "IO", label: 'Indijos Vandenyno Britų Sritis'},
    { code: "ID", label: 'Indonezija'},
    { code: "HK", label: 'Honkongas'},
    { code: "MO", label: 'Makao'},
    { code: "IQ", label: 'Irakas'},
    { code: "IR", label: 'Iranas'},
    { code: "IS", label: 'Islandija'},
    { code: "ES", label: 'Ispanija'},
    { code: "IT", label: 'Italija'},
    { code: "IL", label: 'Izraelis'},
    { code: "JM", label: 'Jamaika'},
    { code: "JP", label: 'Japonija'},
    { code: "YE", label: 'Jemenas'},
    { code: "JO", label: 'Jordanija'},
    { code: "GB", label: 'Jungtinė Karalystė'},
    { code: "US", label: 'Jungtinės Valstijos'},
    { code: "AE", label: 'Jungtiniai Arabų Emyratai'},
    { code: "UM", label: 'Jungtinių Valstijų Mažosios Tolimosios Salos'},
    { code: "VI", label: 'Jungtinių Valstijų Mergelių Salos'},
    { code: "ME", label: 'Juodkalnija'},
    { code: "KY", label: 'Kaimanų Salos'},
    { code: "CX", label: 'Kalėdų Sala'},
    { code: "KH", label: 'Kambodža'},
    { code: "CM", label: 'Kamerūnas'},
    { code: "CA", label: 'Kanada'},
    { code: "IC", label: 'Kanarų salos'},
    { code: "BQ", label: 'Karibų Nyderlandai'},
    { code: "QA", label: 'Kataras'},
    { code: "KZ", label: 'Kazachstanas'},
    { code: "KE", label: 'Kenija'},
    { code: "CN", label: 'Kinija'},
    { code: "CY", label: 'Kipras'},
    { code: "KG", label: 'Kirgizija'},
    { code: "KI", label: 'Kiribatis'},
    { code: "CW", label: 'Kiurasao'},
    { code: "CC", label: 'Kokosų (Kilingo) Salos'},
    { code: "CO", label: 'Kolumbija'},
    { code: "KM", label: 'Komorai'},
    { code: "CG", label: 'Kongas-Brazavilis'},
    { code: "CD", label: 'Kongas-Kinšasa'},
    { code: "XK", label: 'Kosovas'},
    { code: "CR", label: 'Kosta Rika'},
    { code: "HR", label: 'Kroatija'},
    { code: "CU", label: 'Kuba'},
    { code: "CK", label: 'Kuko Salos'},
    { code: "KW", label: 'Kuveitas'},
    { code: "LA", label: 'Laosas'},
    { code: "LV", label: 'Latvija'},
    { code: "PL", label: 'Lenkija'},
    { code: "LS", label: 'Lesotas'},
    { code: "LB", label: 'Libanas'},
    { code: "LR", label: 'Liberija'},
    { code: "LY", label: 'Libija'},
    { code: "LI", label: 'Lichtenšteinas'},
    { code: "LT", label: 'Lietuva'},
    { code: "LU", label: 'Liuksemburgas'},
    { code: "MG", label: 'Madagaskaras'},
    { code: "YT", label: 'Majotas'},
    { code: "MY", label: 'Malaizija'},
    { code: "MW", label: 'Malavis'},
    { code: "MV", label: 'Maldyvai'},
    { code: "ML", label: 'Malis'},
    { code: "MT", label: 'Malta'},
    { code: "MP", label: 'Marianos Šiaurinės Salos'},
    { code: "MA", label: 'Marokas'},
    { code: "MH", label: 'Maršalo Salos'},
    { code: "MQ", label: 'Martinika'},
    { code: "MU", label: 'Mauricijus'},
    { code: "MR", label: 'Mauritanija'},
    { code: "MX", label: 'Meksika'},
    { code: "IM", label: 'Meno Sala'},
    { code: "MM", label: 'Mianmaras (Birma)'},
    { code: "FM", label: 'Mikronezija'},
    { code: "MD", label: 'Moldova'},
    { code: "MC", label: 'Monakas'},
    { code: "MN", label: 'Mongolija'},
    { code: "MS", label: 'Montseratas'},
    { code: "MZ", label: 'Mozambikas'},
    { code: "NA", label: 'Namibija'},
    { code: "NC", label: 'Naujoji Kaledonija'},
    { code: "NZ", label: 'Naujoji Zelandija'},
    { code: "NR", label: 'Nauru'},
    { code: "NP", label: 'Nepalas'},
    { code: "NL", label: 'Nyderlandai'},
    { code: "NG", label: 'Nigerija'},
    { code: "NE", label: 'Nigeris'},
    { code: "NI", label: 'Nikaragva'},
    { code: "NU", label: 'Niujė'},
    { code: "NF", label: 'Norfolko sala'},
    { code: "NO", label: 'Norvegija'},
    { code: "OM", label: 'Omanas'},
    { code: "PK", label: 'Pakistanas'},
    { code: "PW", label: 'Palau'},
    { code: "PS", label: 'Palestinos teritorija'},
    { code: "PA", label: 'Panama'},
    { code: "PG", label: 'Papua Naujoji Gvinėja'},
    { code: "PY", label: 'Paragvajus'},
    { code: "PE", label: 'Peru'},
    { code: "ZA", label: 'Pietų Afrika'},
    { code: "GS", label: 'Pietų Džordžija ir Pietų Sandvičo salos'},
    { code: "KR", label: 'Pietų Korėja'},
    { code: "SS", label: 'Pietų Sudanas'},
    { code: "PN", label: 'Pitkerno salos'},
    { code: "PT", label: 'Portugalija'},
    { code: "FR", label: 'Prancūzija'},
    { code: "GF", label: 'Prancūzijos Gviana'},
    { code: "TF", label: 'Prancūzijos Pietų sritys'},
    { code: "PF", label: 'Prancūzijos Polinezija'},
    { code: "PR", label: 'Puerto Rikas'},
    { code: "GQ", label: 'Pusiaujo Gvinėja'},
    { code: "RE", label: 'Reunjonas'},
    { code: "TL", label: 'Rytų Timoras'},
    { code: "RW", label: 'Ruanda'},
    { code: "RO", label: 'Rumunija'},
    { code: "RU", label: 'Rusija'},
    { code: "SB", label: 'Saliamono Salos'},
    { code: "SV", label: 'Salvadoras'},
    { code: "WS", label: 'Samoa'},
    { code: "SM", label: 'San Marinas'},
    { code: "ST", label: 'San Tomė ir Prinsipė'},
    { code: "SA", label: 'Saudo Arabija'},
    { code: "SC", label: 'Seišeliai'},
    { code: "BL", label: 'Sen Bartelemi'},
    { code: "MF", label: 'Sen Martenas'},
    { code: "PM", label: 'Sen Pjeras ir Mikelonas'},
    { code: "SN", label: 'Senegalas'},
    { code: "KN", label: 'Sent Kitsas ir Nevis'},
    { code: "LC", label: 'Sent Lusija'},
    { code: "RS", label: 'Serbija'},
    { code: "EA", label: 'Seuta ir Melila'},
    { code: "SL", label: 'Siera Leonė'},
    { code: "SG", label: 'Singapūras'},
    { code: "SX", label: 'Sint Martenas'},
    { code: "SY", label: 'Sirija'},
    { code: "SK", label: 'Slovakija'},
    { code: "SI", label: 'Slovėnija'},
    { code: "SO", label: 'Somalis'},
    { code: "SD", label: 'Sudanas'},
    { code: "FI", label: 'Suomija'},
    { code: "SR", label: 'Surinamas'},
    { code: "SJ", label: 'Svalbardas ir Janas Majenas'},
    { code: "SZ", label: 'Svazilandas'},
    { code: "KP", label: 'Šiaurės Korėja'},
    { code: "MK", label: 'Šiaurės Makedonija'},
    { code: "LK", label: 'Šri Lanka'},
    { code: "SH", label: 'Šv. Elenos Sala'},
    { code: "SE", label: 'Švedija'},
    { code: "CH", label: 'Šveicarija'},
    { code: "VC", label: 'Šventasis Vincentas ir Grenadinai'},
    { code: "TJ", label: 'Tadžikija'},
    { code: "TH", label: 'Tailandas'},
    { code: "TW", label: 'Taivanas'},
    { code: "TZ", label: 'Tanzanija'},
    { code: "TC", label: 'Terkso ir Kaikoso Salos'},
    { code: "TG", label: 'Togas'},
    { code: "TK", label: 'Tokelau'},
    { code: "TO", label: 'Tonga'},
    { code: "TT", label: 'Trinidadas ir Tobagas'},
    { code: "TA", label: 'Tristanas da Kunja'},
    { code: "TN", label: 'Tunisas'},
    { code: "TR", label: 'Turkija'},
    { code: "TM", label: 'Turkmėnistanas'},
    { code: "TV", label: 'Tuvalu'},
    { code: "UG", label: 'Uganda'},
    { code: "UA", label: 'Ukraina'},
    { code: "UY", label: 'Urugvajus'},
    { code: "UZ", label: 'Uzbekistanas'},
    { code: "EH", label: 'Vakarų Sachara'},
    { code: "VU", label: 'Vanuatu'},
    { code: "VA", label: 'Vatikano Miesto Valstybė'},
    { code: "VE", label: 'Venesuela'},
    { code: "HU", label: 'Vengrija'},
    { code: "VN", label: 'Vietnamas'},
    { code: "DE", label: 'Vokietija'},
    { code: "WF", label: 'Volisas ir Futūna'},
    { code: "ZM", label: 'Zambija'},
    { code: "ZW", label: 'Zimbabvė'},
    { code: "CV", label: 'Žaliasis Kyšulys'}
]